// C++ implementation of the Blue Robotics 'Ping' binary message protocol

//~!~!~!~!~!~!~!~!~!~!~!~!~!~!~!~!~!~!~!~!~!~!~!~!~!~!~!~!~!
// THIS IS AN AUTOGENERATED FILE
// DO NOT EDIT
//~!~!~!~!~!~!~!~!~!~!~!~!~!~!~!~!~!~!~!~!~!~!~!~!~!~!~!~!~!

#pragma once

#include "ping-message.h"

struct atof_t {
    float    angle;            // radians, positive to port
    float    tof;              // seconds, time of flight
    uint32_t      reserved[2];
};
// float distance = 0.5 * speed_of_sound * tof_sec;
// float y = distance * sin(angle);
// float z = -distance * cos(angle);

inline const char* to_string(atof_t* data)
{
  (void) data;
  return "placeholder data";
}

inline const char* to_string(float* float_data)
{
  (void) float_data;
  return "placeholder data";
}

// TODO: should maybe be an enum
namespace Surveyor240Id
{
    static const uint16_t SET_NET_INFO = 17;
    static const uint16_t SET_PING_PARAMETERS = 3023;
    static const uint16_t UTC_RESPONSE = 15;
    static const uint16_t UTC_REQUEST = 14;
    static const uint16_t JSON_WRAPPER = 10;
    static const uint16_t ATOF_POINT_DATA = 3012;
    static const uint16_t ATTITUDE_REPORT = 504;
    static const uint16_t WATER_STATS = 118;
    static const uint16_t YZ_POINT_DATA = 3011;
}

class surveyor240_set_net_info : public ping_message
{
public:
    surveyor240_set_net_info(const ping_message& msg) : ping_message { msg } {}
    surveyor240_set_net_info(uint8_t* buf) : ping_message { buf, static_cast<uint16_t>(22) }
    {
        msgData[0] = 'B';
        msgData[1] = 'R';
        reinterpret_cast<uint16_t&>(msgData[2]) = static_cast<uint16_t>(12); // payload size
        reinterpret_cast<uint16_t&>(msgData[4]) = 17; // ID
        msgData[6] = 0;
        msgData[7] = 0;
    }
    surveyor240_set_net_info(const uint8_t* buf, const uint16_t length) : ping_message { buf, length } {}
    surveyor240_set_net_info() : ping_message { static_cast<uint16_t>(22) }
    {
        msgData[0] = 'B';
        msgData[1] = 'R';
        reinterpret_cast<uint16_t&>(msgData[2]) = static_cast<uint16_t>(12); // payload size
        reinterpret_cast<uint16_t&>(msgData[4]) = 17; // ID
        msgData[6] = 0;
        msgData[7] = 0;
    }

    uint32_t ntp_ip_address() const { return reinterpret_cast<uint32_t&>(msgData[headerLength + 0]); }
    void set_ntp_ip_address(const uint32_t ntp_ip_address) { reinterpret_cast<uint32_t&>(msgData[headerLength + 0]) = ntp_ip_address; }
    uint32_t subnet_mask() const { return reinterpret_cast<uint32_t&>(msgData[headerLength + 4]); }
    void set_subnet_mask(const uint32_t subnet_mask) { reinterpret_cast<uint32_t&>(msgData[headerLength + 4]) = subnet_mask; }
    uint32_t gateway_ip() const { return reinterpret_cast<uint32_t&>(msgData[headerLength + 8]); }
    void set_gateway_ip(const uint32_t gateway_ip) { reinterpret_cast<uint32_t&>(msgData[headerLength + 8]) = gateway_ip; }

    int getMessageAsString(char* string, size_t size) const {
        int written = ping_message::getMessageAsString(string, size);
        if (written > 0 && written < static_cast<int>(size)) {
            return snprintf(string + written, size - static_cast<size_t>(written),
                "  ntp_ip_address: %" PRIu32 "\n"
                "  subnet_mask: %" PRIu32 "\n"
                "  gateway_ip: %" PRIu32 "\n"
                , ntp_ip_address()
                , subnet_mask()
                , gateway_ip()
            );
        }
        return written;
    }
};

class surveyor240_set_ping_parameters : public ping_message
{
public:
    surveyor240_set_ping_parameters(const ping_message& msg) : ping_message { msg } {}
    surveyor240_set_ping_parameters(uint8_t* buf) : ping_message { buf, static_cast<uint16_t>(46) }
    {
        msgData[0] = 'B';
        msgData[1] = 'R';
        reinterpret_cast<uint16_t&>(msgData[2]) = static_cast<uint16_t>(36); // payload size
        reinterpret_cast<uint16_t&>(msgData[4]) = 3023; // ID
        msgData[6] = 0;
        msgData[7] = 0;
    }
    surveyor240_set_ping_parameters(const uint8_t* buf, const uint16_t length) : ping_message { buf, length } {}
    surveyor240_set_ping_parameters() : ping_message { static_cast<uint16_t>(46) }
    {
        msgData[0] = 'B';
        msgData[1] = 'R';
        reinterpret_cast<uint16_t&>(msgData[2]) = static_cast<uint16_t>(36); // payload size
        reinterpret_cast<uint16_t&>(msgData[4]) = 3023; // ID
        msgData[6] = 0;
        msgData[7] = 0;
    }

    int32_t start_mm() const { return reinterpret_cast<int32_t&>(msgData[headerLength + 0]); }
    void set_start_mm(const int32_t start_mm) { reinterpret_cast<int32_t&>(msgData[headerLength + 0]) = start_mm; }
    int32_t end_mm() const { return reinterpret_cast<int32_t&>(msgData[headerLength + 4]); }
    void set_end_mm(const int32_t end_mm) { reinterpret_cast<int32_t&>(msgData[headerLength + 4]) = end_mm; }
    float sos_mps() const { return reinterpret_cast<float&>(msgData[headerLength + 8]); }
    void set_sos_mps(const float sos_mps) { reinterpret_cast<float&>(msgData[headerLength + 8]) = sos_mps; }
    int16_t gain_index() const { return reinterpret_cast<int16_t&>(msgData[headerLength + 12]); }
    void set_gain_index(const int16_t gain_index) { reinterpret_cast<int16_t&>(msgData[headerLength + 12]) = gain_index; }
    int16_t msec_per_ping() const { return reinterpret_cast<int16_t&>(msgData[headerLength + 14]); }
    void set_msec_per_ping(const int16_t msec_per_ping) { reinterpret_cast<int16_t&>(msgData[headerLength + 14]) = msec_per_ping; }
    uint16_t deprecated() const { return reinterpret_cast<uint16_t&>(msgData[headerLength + 16]); }
    void set_deprecated(const uint16_t deprecated) { reinterpret_cast<uint16_t&>(msgData[headerLength + 16]) = deprecated; }
    uint8_t diagnostic_injected_signal() const { return reinterpret_cast<uint8_t&>(msgData[headerLength + 18]); }
    void set_diagnostic_injected_signal(const uint8_t diagnostic_injected_signal) { reinterpret_cast<uint8_t&>(msgData[headerLength + 18]) = diagnostic_injected_signal; }
    bool ping_enable() const { return reinterpret_cast<bool&>(msgData[headerLength + 19]); }
    void set_ping_enable(const bool ping_enable) { reinterpret_cast<bool&>(msgData[headerLength + 19]) = ping_enable; }
    bool enable_channel_data() const { return reinterpret_cast<bool&>(msgData[headerLength + 20]); }
    void set_enable_channel_data(const bool enable_channel_data) { reinterpret_cast<bool&>(msgData[headerLength + 20]) = enable_channel_data; }
    bool reserved_for_raw_data() const { return reinterpret_cast<bool&>(msgData[headerLength + 21]); }
    void set_reserved_for_raw_data(const bool reserved_for_raw_data) { reinterpret_cast<bool&>(msgData[headerLength + 21]) = reserved_for_raw_data; }
    bool enable_yz_point_data() const { return reinterpret_cast<bool&>(msgData[headerLength + 22]); }
    void set_enable_yz_point_data(const bool enable_yz_point_data) { reinterpret_cast<bool&>(msgData[headerLength + 22]) = enable_yz_point_data; }
    bool enable_atof_data() const { return reinterpret_cast<bool&>(msgData[headerLength + 23]); }
    void set_enable_atof_data(const bool enable_atof_data) { reinterpret_cast<bool&>(msgData[headerLength + 23]) = enable_atof_data; }
    int32_t target_ping_hz() const { return reinterpret_cast<int32_t&>(msgData[headerLength + 24]); }
    void set_target_ping_hz(const int32_t target_ping_hz) { reinterpret_cast<int32_t&>(msgData[headerLength + 24]) = target_ping_hz; }
    uint16_t n_range_steps() const { return reinterpret_cast<uint16_t&>(msgData[headerLength + 28]); }
    void set_n_range_steps(const uint16_t n_range_steps) { reinterpret_cast<uint16_t&>(msgData[headerLength + 28]) = n_range_steps; }
    uint16_t reserved() const { return reinterpret_cast<uint16_t&>(msgData[headerLength + 30]); }
    void set_reserved(const uint16_t reserved) { reinterpret_cast<uint16_t&>(msgData[headerLength + 30]) = reserved; }
    float pulse_len_steps() const { return reinterpret_cast<float&>(msgData[headerLength + 32]); }
    void set_pulse_len_steps(const float pulse_len_steps) { reinterpret_cast<float&>(msgData[headerLength + 32]) = pulse_len_steps; }

    int getMessageAsString(char* string, size_t size) const {
        int written = ping_message::getMessageAsString(string, size);
        if (written > 0 && written < static_cast<int>(size)) {
            return snprintf(string + written, size - static_cast<size_t>(written),
                "  start_mm: %" PRId32 "\n"
                "  end_mm: %" PRId32 "\n"
                "  sos_mps: %" "f" "\n"
                "  gain_index: %" PRId16 "\n"
                "  msec_per_ping: %" PRId16 "\n"
                "  deprecated: %" PRIu16 "\n"
                "  diagnostic_injected_signal: %" PRIu8 "\n"
                "  ping_enable: %" "d" "\n"
                "  enable_channel_data: %" "d" "\n"
                "  reserved_for_raw_data: %" "d" "\n"
                "  enable_yz_point_data: %" "d" "\n"
                "  enable_atof_data: %" "d" "\n"
                "  target_ping_hz: %" PRId32 "\n"
                "  n_range_steps: %" PRIu16 "\n"
                "  reserved: %" PRIu16 "\n"
                "  pulse_len_steps: %" "f" "\n"
                , start_mm()
                , end_mm()
                , sos_mps()
                , gain_index()
                , msec_per_ping()
                , deprecated()
                , diagnostic_injected_signal()
                , ping_enable()
                , enable_channel_data()
                , reserved_for_raw_data()
                , enable_yz_point_data()
                , enable_atof_data()
                , target_ping_hz()
                , n_range_steps()
                , reserved()
                , pulse_len_steps()
            );
        }
        return written;
    }
};

class surveyor240_utc_response : public ping_message
{
public:
    surveyor240_utc_response(const ping_message& msg) : ping_message { msg } {}
    surveyor240_utc_response(uint8_t* buf) : ping_message { buf, static_cast<uint16_t>(22) }
    {
        msgData[0] = 'B';
        msgData[1] = 'R';
        reinterpret_cast<uint16_t&>(msgData[2]) = static_cast<uint16_t>(12); // payload size
        reinterpret_cast<uint16_t&>(msgData[4]) = 15; // ID
        msgData[6] = 0;
        msgData[7] = 0;
    }
    surveyor240_utc_response(const uint8_t* buf, const uint16_t length) : ping_message { buf, length } {}
    surveyor240_utc_response() : ping_message { static_cast<uint16_t>(22) }
    {
        msgData[0] = 'B';
        msgData[1] = 'R';
        reinterpret_cast<uint16_t&>(msgData[2]) = static_cast<uint16_t>(12); // payload size
        reinterpret_cast<uint16_t&>(msgData[4]) = 15; // ID
        msgData[6] = 0;
        msgData[7] = 0;
    }

    uint64_t utc_msec() const { return reinterpret_cast<uint64_t&>(msgData[headerLength + 0]); }
    void set_utc_msec(const uint64_t utc_msec) { reinterpret_cast<uint64_t&>(msgData[headerLength + 0]) = utc_msec; }
    uint32_t accuracy_msec() const { return reinterpret_cast<uint32_t&>(msgData[headerLength + 8]); }
    void set_accuracy_msec(const uint32_t accuracy_msec) { reinterpret_cast<uint32_t&>(msgData[headerLength + 8]) = accuracy_msec; }

    int getMessageAsString(char* string, size_t size) const {
        int written = ping_message::getMessageAsString(string, size);
        if (written > 0 && written < static_cast<int>(size)) {
            return snprintf(string + written, size - static_cast<size_t>(written),
                "  utc_msec: %" PRIu64 "\n"
                "  accuracy_msec: %" PRIu32 "\n"
                , utc_msec()
                , accuracy_msec()
            );
        }
        return written;
    }
};

class surveyor240_utc_request : public ping_message
{
public:
    surveyor240_utc_request(const ping_message& msg) : ping_message { msg } {}
    surveyor240_utc_request(uint8_t* buf) : ping_message { buf, static_cast<uint16_t>(10) }
    {
        msgData[0] = 'B';
        msgData[1] = 'R';
        reinterpret_cast<uint16_t&>(msgData[2]) = static_cast<uint16_t>(0); // payload size
        reinterpret_cast<uint16_t&>(msgData[4]) = 14; // ID
        msgData[6] = 0;
        msgData[7] = 0;
    }
    surveyor240_utc_request(const uint8_t* buf, const uint16_t length) : ping_message { buf, length } {}
    surveyor240_utc_request() : ping_message { static_cast<uint16_t>(10) }
    {
        msgData[0] = 'B';
        msgData[1] = 'R';
        reinterpret_cast<uint16_t&>(msgData[2]) = static_cast<uint16_t>(0); // payload size
        reinterpret_cast<uint16_t&>(msgData[4]) = 14; // ID
        msgData[6] = 0;
        msgData[7] = 0;
    }

};

class surveyor240_JSON_WRAPPER : public ping_message
{
public:
    surveyor240_JSON_WRAPPER(const ping_message& msg) : ping_message { msg } {}
    surveyor240_JSON_WRAPPER(uint8_t* buf,
uint16_t string_length) : ping_message { buf, static_cast<uint16_t>(10 + string_length) }
    {
        msgData[0] = 'B';
        msgData[1] = 'R';
        reinterpret_cast<uint16_t&>(msgData[2]) = static_cast<uint16_t>(0 + string_length); // payload size
        reinterpret_cast<uint16_t&>(msgData[4]) = 10; // ID
        msgData[6] = 0;
        msgData[7] = 0;
    }
    surveyor240_JSON_WRAPPER(const uint8_t* buf, const uint16_t length) : ping_message { buf, length } {}
    surveyor240_JSON_WRAPPER(uint16_t string_length) : ping_message { static_cast<uint16_t>(10 + string_length) }
    {
        msgData[0] = 'B';
        msgData[1] = 'R';
        reinterpret_cast<uint16_t&>(msgData[2]) = static_cast<uint16_t>(0 + string_length); // payload size
        reinterpret_cast<uint16_t&>(msgData[4]) = 10; // ID
        msgData[6] = 0;
        msgData[7] = 0;
    }

    char* string_() const { return reinterpret_cast<char*>(msgData+headerLength+0); }
    void set_string_at(const uint16_t i, const char data) { reinterpret_cast<char&>(msgData[headerLength + 0 + i]) = data; }

    int getMessageAsString(char* string, size_t size) const {
        int written = ping_message::getMessageAsString(string, size);
        if (written > 0 && written < static_cast<int>(size)) {
            return snprintf(string + written, size - static_cast<size_t>(written),
                "  string: %s\n"
                , string_()
            );
        }
        return written;
    }
};

class surveyor240_atof_point_data : public ping_message
{
public:
    surveyor240_atof_point_data(const ping_message& msg) : ping_message { msg } {}
    surveyor240_atof_point_data(uint8_t* buf,
uint16_t atof_point_data_length) : ping_message { buf, static_cast<uint16_t>(50 + atof_point_data_length) }
    {
        msgData[0] = 'B';
        msgData[1] = 'R';
        reinterpret_cast<uint16_t&>(msgData[2]) = static_cast<uint16_t>(40 + atof_point_data_length); // payload size
        reinterpret_cast<uint16_t&>(msgData[4]) = 3012; // ID
        msgData[6] = 0;
        msgData[7] = 0;
    }
    surveyor240_atof_point_data(const uint8_t* buf, const uint16_t length) : ping_message { buf, length } {}
    surveyor240_atof_point_data(uint16_t atof_point_data_length) : ping_message { static_cast<uint16_t>(50 + atof_point_data_length) }
    {
        msgData[0] = 'B';
        msgData[1] = 'R';
        reinterpret_cast<uint16_t&>(msgData[2]) = static_cast<uint16_t>(40 + atof_point_data_length); // payload size
        reinterpret_cast<uint16_t&>(msgData[4]) = 3012; // ID
        msgData[6] = 0;
        msgData[7] = 0;
    }

    uint32_t pwr_up_msec() const { return reinterpret_cast<uint32_t&>(msgData[headerLength + 0]); }
    void set_pwr_up_msec(const uint32_t pwr_up_msec) { reinterpret_cast<uint32_t&>(msgData[headerLength + 0]) = pwr_up_msec; }
    uint64_t utc_msec() const { return reinterpret_cast<uint64_t&>(msgData[headerLength + 4]); }
    void set_utc_msec(const uint64_t utc_msec) { reinterpret_cast<uint64_t&>(msgData[headerLength + 4]) = utc_msec; }
    float listening_sec() const { return reinterpret_cast<float&>(msgData[headerLength + 12]); }
    void set_listening_sec(const float listening_sec) { reinterpret_cast<float&>(msgData[headerLength + 12]) = listening_sec; }
    float sos_mps() const { return reinterpret_cast<float&>(msgData[headerLength + 16]); }
    void set_sos_mps(const float sos_mps) { reinterpret_cast<float&>(msgData[headerLength + 16]) = sos_mps; }
    uint32_t ping_number() const { return reinterpret_cast<uint32_t&>(msgData[headerLength + 20]); }
    void set_ping_number(const uint32_t ping_number) { reinterpret_cast<uint32_t&>(msgData[headerLength + 20]) = ping_number; }
    uint32_t ping_hz() const { return reinterpret_cast<uint32_t&>(msgData[headerLength + 24]); }
    void set_ping_hz(const uint32_t ping_hz) { reinterpret_cast<uint32_t&>(msgData[headerLength + 24]) = ping_hz; }
    float pulse_sec() const { return reinterpret_cast<float&>(msgData[headerLength + 28]); }
    void set_pulse_sec(const float pulse_sec) { reinterpret_cast<float&>(msgData[headerLength + 28]) = pulse_sec; }
    uint32_t flags() const { return reinterpret_cast<uint32_t&>(msgData[headerLength + 32]); }
    void set_flags(const uint32_t flags) { reinterpret_cast<uint32_t&>(msgData[headerLength + 32]) = flags; }
    uint16_t num_points() const { return reinterpret_cast<uint16_t&>(msgData[headerLength + 36]); }
    void set_num_points(const uint16_t num_points) { reinterpret_cast<uint16_t&>(msgData[headerLength + 36]) = num_points; }
    uint16_t reserved() const { return reinterpret_cast<uint16_t&>(msgData[headerLength + 38]); }
    void set_reserved(const uint16_t reserved) { reinterpret_cast<uint16_t&>(msgData[headerLength + 38]) = reserved; }
    atof_t* atof_point_data() const { return reinterpret_cast<atof_t*>(msgData+headerLength+40); }
    void set_atof_point_data_at(const uint16_t i, const atof_t data) { reinterpret_cast<atof_t&>(msgData[headerLength + 40 + i]) = data; }

    int getMessageAsString(char* string, size_t size) const {
        int written = ping_message::getMessageAsString(string, size);
        if (written > 0 && written < static_cast<int>(size)) {
            return snprintf(string + written, size - static_cast<size_t>(written),
                "  pwr_up_msec: %" PRIu32 "\n"
                "  utc_msec: %" PRIu64 "\n"
                "  listening_sec: %" "f" "\n"
                "  sos_mps: %" "f" "\n"
                "  ping_number: %" PRIu32 "\n"
                "  ping_hz: %" PRIu32 "\n"
                "  pulse_sec: %" "f" "\n"
                "  flags: %" PRIu32 "\n"
                "  num_points: %" PRIu16 "\n"
                "  reserved: %" PRIu16 "\n"
                "  atof_point_data: %s\n"
                , pwr_up_msec()
                , utc_msec()
                , listening_sec()
                , sos_mps()
                , ping_number()
                , ping_hz()
                , pulse_sec()
                , flags()
                , num_points()
                , reserved()
                , to_string(atof_point_data())
            );
        }
        return written;
    }
};

class surveyor240_attitude_report : public ping_message
{
public:
    surveyor240_attitude_report(const ping_message& msg) : ping_message { msg } {}
    surveyor240_attitude_report(uint8_t* buf) : ping_message { buf, static_cast<uint16_t>(46) }
    {
        msgData[0] = 'B';
        msgData[1] = 'R';
        reinterpret_cast<uint16_t&>(msgData[2]) = static_cast<uint16_t>(36); // payload size
        reinterpret_cast<uint16_t&>(msgData[4]) = 504; // ID
        msgData[6] = 0;
        msgData[7] = 0;
    }
    surveyor240_attitude_report(const uint8_t* buf, const uint16_t length) : ping_message { buf, length } {}
    surveyor240_attitude_report() : ping_message { static_cast<uint16_t>(46) }
    {
        msgData[0] = 'B';
        msgData[1] = 'R';
        reinterpret_cast<uint16_t&>(msgData[2]) = static_cast<uint16_t>(36); // payload size
        reinterpret_cast<uint16_t&>(msgData[4]) = 504; // ID
        msgData[6] = 0;
        msgData[7] = 0;
    }

    float up_vec_x() const { return reinterpret_cast<float&>(msgData[headerLength + 0]); }
    void set_up_vec_x(const float up_vec_x) { reinterpret_cast<float&>(msgData[headerLength + 0]) = up_vec_x; }
    float up_vec_y() const { return reinterpret_cast<float&>(msgData[headerLength + 4]); }
    void set_up_vec_y(const float up_vec_y) { reinterpret_cast<float&>(msgData[headerLength + 4]) = up_vec_y; }
    float up_vec_z() const { return reinterpret_cast<float&>(msgData[headerLength + 8]); }
    void set_up_vec_z(const float up_vec_z) { reinterpret_cast<float&>(msgData[headerLength + 8]) = up_vec_z; }
    float reserved_1() const { return reinterpret_cast<float&>(msgData[headerLength + 12]); }
    void set_reserved_1(const float reserved_1) { reinterpret_cast<float&>(msgData[headerLength + 12]) = reserved_1; }
    float reserved_2() const { return reinterpret_cast<float&>(msgData[headerLength + 16]); }
    void set_reserved_2(const float reserved_2) { reinterpret_cast<float&>(msgData[headerLength + 16]) = reserved_2; }
    float reserved_3() const { return reinterpret_cast<float&>(msgData[headerLength + 20]); }
    void set_reserved_3(const float reserved_3) { reinterpret_cast<float&>(msgData[headerLength + 20]) = reserved_3; }
    uint64_t utc_msec() const { return reinterpret_cast<uint64_t&>(msgData[headerLength + 24]); }
    void set_utc_msec(const uint64_t utc_msec) { reinterpret_cast<uint64_t&>(msgData[headerLength + 24]) = utc_msec; }
    uint32_t pwr_up_msec() const { return reinterpret_cast<uint32_t&>(msgData[headerLength + 32]); }
    void set_pwr_up_msec(const uint32_t pwr_up_msec) { reinterpret_cast<uint32_t&>(msgData[headerLength + 32]) = pwr_up_msec; }

    int getMessageAsString(char* string, size_t size) const {
        int written = ping_message::getMessageAsString(string, size);
        if (written > 0 && written < static_cast<int>(size)) {
            return snprintf(string + written, size - static_cast<size_t>(written),
                "  up_vec_x: %" "f" "\n"
                "  up_vec_y: %" "f" "\n"
                "  up_vec_z: %" "f" "\n"
                "  reserved_1: %" "f" "\n"
                "  reserved_2: %" "f" "\n"
                "  reserved_3: %" "f" "\n"
                "  utc_msec: %" PRIu64 "\n"
                "  pwr_up_msec: %" PRIu32 "\n"
                , up_vec_x()
                , up_vec_y()
                , up_vec_z()
                , reserved_1()
                , reserved_2()
                , reserved_3()
                , utc_msec()
                , pwr_up_msec()
            );
        }
        return written;
    }
};

class surveyor240_water_stats : public ping_message
{
public:
    surveyor240_water_stats(const ping_message& msg) : ping_message { msg } {}
    surveyor240_water_stats(uint8_t* buf) : ping_message { buf, static_cast<uint16_t>(18) }
    {
        msgData[0] = 'B';
        msgData[1] = 'R';
        reinterpret_cast<uint16_t&>(msgData[2]) = static_cast<uint16_t>(8); // payload size
        reinterpret_cast<uint16_t&>(msgData[4]) = 118; // ID
        msgData[6] = 0;
        msgData[7] = 0;
    }
    surveyor240_water_stats(const uint8_t* buf, const uint16_t length) : ping_message { buf, length } {}
    surveyor240_water_stats() : ping_message { static_cast<uint16_t>(18) }
    {
        msgData[0] = 'B';
        msgData[1] = 'R';
        reinterpret_cast<uint16_t&>(msgData[2]) = static_cast<uint16_t>(8); // payload size
        reinterpret_cast<uint16_t&>(msgData[4]) = 118; // ID
        msgData[6] = 0;
        msgData[7] = 0;
    }

    float temperature() const { return reinterpret_cast<float&>(msgData[headerLength + 0]); }
    void set_temperature(const float temperature) { reinterpret_cast<float&>(msgData[headerLength + 0]) = temperature; }
    float pressure() const { return reinterpret_cast<float&>(msgData[headerLength + 4]); }
    void set_pressure(const float pressure) { reinterpret_cast<float&>(msgData[headerLength + 4]) = pressure; }

    int getMessageAsString(char* string, size_t size) const {
        int written = ping_message::getMessageAsString(string, size);
        if (written > 0 && written < static_cast<int>(size)) {
            return snprintf(string + written, size - static_cast<size_t>(written),
                "  temperature: %" "f" "\n"
                "  pressure: %" "f" "\n"
                , temperature()
                , pressure()
            );
        }
        return written;
    }
};

class surveyor240_yz_point_data : public ping_message
{
public:
    surveyor240_yz_point_data(const ping_message& msg) : ping_message { msg } {}
    surveyor240_yz_point_data(uint8_t* buf,
uint16_t yz_point_data_length) : ping_message { buf, static_cast<uint16_t>(110 + yz_point_data_length) }
    {
        msgData[0] = 'B';
        msgData[1] = 'R';
        reinterpret_cast<uint16_t&>(msgData[2]) = static_cast<uint16_t>(100 + yz_point_data_length); // payload size
        reinterpret_cast<uint16_t&>(msgData[4]) = 3011; // ID
        msgData[6] = 0;
        msgData[7] = 0;
    }
    surveyor240_yz_point_data(const uint8_t* buf, const uint16_t length) : ping_message { buf, length } {}
    surveyor240_yz_point_data(uint16_t yz_point_data_length) : ping_message { static_cast<uint16_t>(110 + yz_point_data_length) }
    {
        msgData[0] = 'B';
        msgData[1] = 'R';
        reinterpret_cast<uint16_t&>(msgData[2]) = static_cast<uint16_t>(100 + yz_point_data_length); // payload size
        reinterpret_cast<uint16_t&>(msgData[4]) = 3011; // ID
        msgData[6] = 0;
        msgData[7] = 0;
    }

    uint32_t timestamp_msec() const { return reinterpret_cast<uint32_t&>(msgData[headerLength + 0]); }
    void set_timestamp_msec(const uint32_t timestamp_msec) { reinterpret_cast<uint32_t&>(msgData[headerLength + 0]) = timestamp_msec; }
    uint32_t ping_number() const { return reinterpret_cast<uint32_t&>(msgData[headerLength + 4]); }
    void set_ping_number(const uint32_t ping_number) { reinterpret_cast<uint32_t&>(msgData[headerLength + 4]) = ping_number; }
    float sos_mps() const { return reinterpret_cast<float&>(msgData[headerLength + 8]); }
    void set_sos_mps(const float sos_mps) { reinterpret_cast<float&>(msgData[headerLength + 8]) = sos_mps; }
    float up_vec_x() const { return reinterpret_cast<float&>(msgData[headerLength + 12]); }
    void set_up_vec_x(const float up_vec_x) { reinterpret_cast<float&>(msgData[headerLength + 12]) = up_vec_x; }
    float up_vec_y() const { return reinterpret_cast<float&>(msgData[headerLength + 16]); }
    void set_up_vec_y(const float up_vec_y) { reinterpret_cast<float&>(msgData[headerLength + 16]) = up_vec_y; }
    float up_vec_z() const { return reinterpret_cast<float&>(msgData[headerLength + 20]); }
    void set_up_vec_z(const float up_vec_z) { reinterpret_cast<float&>(msgData[headerLength + 20]) = up_vec_z; }
    float mag_vec_x() const { return reinterpret_cast<float&>(msgData[headerLength + 24]); }
    void set_mag_vec_x(const float mag_vec_x) { reinterpret_cast<float&>(msgData[headerLength + 24]) = mag_vec_x; }
    float mag_vec_y() const { return reinterpret_cast<float&>(msgData[headerLength + 28]); }
    void set_mag_vec_y(const float mag_vec_y) { reinterpret_cast<float&>(msgData[headerLength + 28]) = mag_vec_y; }
    float mag_vec_z() const { return reinterpret_cast<float&>(msgData[headerLength + 32]); }
    void set_mag_vec_z(const float mag_vec_z) { reinterpret_cast<float&>(msgData[headerLength + 32]) = mag_vec_z; }
    uint32_t reserved_0() const { return reinterpret_cast<uint32_t&>(msgData[headerLength + 36]); }
    void set_reserved_0(const uint32_t reserved_0) { reinterpret_cast<uint32_t&>(msgData[headerLength + 36]) = reserved_0; }
    uint32_t reserved_1() const { return reinterpret_cast<uint32_t&>(msgData[headerLength + 40]); }
    void set_reserved_1(const uint32_t reserved_1) { reinterpret_cast<uint32_t&>(msgData[headerLength + 40]) = reserved_1; }
    uint32_t reserved_2() const { return reinterpret_cast<uint32_t&>(msgData[headerLength + 44]); }
    void set_reserved_2(const uint32_t reserved_2) { reinterpret_cast<uint32_t&>(msgData[headerLength + 44]) = reserved_2; }
    uint32_t reserved_3() const { return reinterpret_cast<uint32_t&>(msgData[headerLength + 48]); }
    void set_reserved_3(const uint32_t reserved_3) { reinterpret_cast<uint32_t&>(msgData[headerLength + 48]) = reserved_3; }
    uint32_t reserved_4() const { return reinterpret_cast<uint32_t&>(msgData[headerLength + 52]); }
    void set_reserved_4(const uint32_t reserved_4) { reinterpret_cast<uint32_t&>(msgData[headerLength + 52]) = reserved_4; }
    uint32_t reserved_5() const { return reinterpret_cast<uint32_t&>(msgData[headerLength + 56]); }
    void set_reserved_5(const uint32_t reserved_5) { reinterpret_cast<uint32_t&>(msgData[headerLength + 56]) = reserved_5; }
    uint32_t reserved_6() const { return reinterpret_cast<uint32_t&>(msgData[headerLength + 60]); }
    void set_reserved_6(const uint32_t reserved_6) { reinterpret_cast<uint32_t&>(msgData[headerLength + 60]) = reserved_6; }
    uint32_t reserved_7() const { return reinterpret_cast<uint32_t&>(msgData[headerLength + 64]); }
    void set_reserved_7(const uint32_t reserved_7) { reinterpret_cast<uint32_t&>(msgData[headerLength + 64]) = reserved_7; }
    uint32_t reserved_8() const { return reinterpret_cast<uint32_t&>(msgData[headerLength + 68]); }
    void set_reserved_8(const uint32_t reserved_8) { reinterpret_cast<uint32_t&>(msgData[headerLength + 68]) = reserved_8; }
    uint32_t reserved_9() const { return reinterpret_cast<uint32_t&>(msgData[headerLength + 72]); }
    void set_reserved_9(const uint32_t reserved_9) { reinterpret_cast<uint32_t&>(msgData[headerLength + 72]) = reserved_9; }
    float water_degC() const { return reinterpret_cast<float&>(msgData[headerLength + 76]); }
    void set_water_degC(const float water_degC) { reinterpret_cast<float&>(msgData[headerLength + 76]) = water_degC; }
    float water_bar() const { return reinterpret_cast<float&>(msgData[headerLength + 80]); }
    void set_water_bar(const float water_bar) { reinterpret_cast<float&>(msgData[headerLength + 80]) = water_bar; }
    float heave_m() const { return reinterpret_cast<float&>(msgData[headerLength + 84]); }
    void set_heave_m(const float heave_m) { reinterpret_cast<float&>(msgData[headerLength + 84]) = heave_m; }
    float start_m() const { return reinterpret_cast<float&>(msgData[headerLength + 88]); }
    void set_start_m(const float start_m) { reinterpret_cast<float&>(msgData[headerLength + 88]) = start_m; }
    float end_m() const { return reinterpret_cast<float&>(msgData[headerLength + 92]); }
    void set_end_m(const float end_m) { reinterpret_cast<float&>(msgData[headerLength + 92]) = end_m; }
    uint16_t unused() const { return reinterpret_cast<uint16_t&>(msgData[headerLength + 96]); }
    void set_unused(const uint16_t unused) { reinterpret_cast<uint16_t&>(msgData[headerLength + 96]) = unused; }
    uint16_t num_points() const { return reinterpret_cast<uint16_t&>(msgData[headerLength + 98]); }
    void set_num_points(const uint16_t num_points) { reinterpret_cast<uint16_t&>(msgData[headerLength + 98]) = num_points; }
    float* yz_point_data() const { return reinterpret_cast<float*>(msgData+headerLength+100); }
    void set_yz_point_data_at(const uint16_t i, const float data) { reinterpret_cast<float&>(msgData[headerLength + 100 + i]) = data; }

    int getMessageAsString(char* string, size_t size) const {
        int written = ping_message::getMessageAsString(string, size);
        if (written > 0 && written < static_cast<int>(size)) {
            return snprintf(string + written, size - static_cast<size_t>(written),
                "  timestamp_msec: %" PRIu32 "\n"
                "  ping_number: %" PRIu32 "\n"
                "  sos_mps: %" "f" "\n"
                "  up_vec_x: %" "f" "\n"
                "  up_vec_y: %" "f" "\n"
                "  up_vec_z: %" "f" "\n"
                "  mag_vec_x: %" "f" "\n"
                "  mag_vec_y: %" "f" "\n"
                "  mag_vec_z: %" "f" "\n"
                "  reserved_0: %" PRIu32 "\n"
                "  reserved_1: %" PRIu32 "\n"
                "  reserved_2: %" PRIu32 "\n"
                "  reserved_3: %" PRIu32 "\n"
                "  reserved_4: %" PRIu32 "\n"
                "  reserved_5: %" PRIu32 "\n"
                "  reserved_6: %" PRIu32 "\n"
                "  reserved_7: %" PRIu32 "\n"
                "  reserved_8: %" PRIu32 "\n"
                "  reserved_9: %" PRIu32 "\n"
                "  water_degC: %" "f" "\n"
                "  water_bar: %" "f" "\n"
                "  heave_m: %" "f" "\n"
                "  start_m: %" "f" "\n"
                "  end_m: %" "f" "\n"
                "  unused: %" PRIu16 "\n"
                "  num_points: %" PRIu16 "\n"
                "  yz_point_data: %s\n"
                , timestamp_msec()
                , ping_number()
                , sos_mps()
                , up_vec_x()
                , up_vec_y()
                , up_vec_z()
                , mag_vec_x()
                , mag_vec_y()
                , mag_vec_z()
                , reserved_0()
                , reserved_1()
                , reserved_2()
                , reserved_3()
                , reserved_4()
                , reserved_5()
                , reserved_6()
                , reserved_7()
                , reserved_8()
                , reserved_9()
                , water_degC()
                , water_bar()
                , heave_m()
                , start_m()
                , end_m()
                , unused()
                , num_points()
                , to_string(yz_point_data())
            );
        }
        return written;
    }
};

