/*
 * A device API for the Blue Robotics Ping Echosounder
 *
 *~!~!~!~!~!~!~!~!~!~!~!~!~!~!~!~!~!~!~!~!~!~!~!~!~!~!~!~!~!
 * THIS IS AN AUTOGENERATED FILE
 * DO NOT EDIT
 *~!~!~!~!~!~!~!~!~!~!~!~!~!~!~!~!~!~!~!~!~!~!~!~!~!~!~!~!~!
 *
 */

#pragma once

#include "ping-device.h"
#include "ping-message-surveyor240.h"

class Surveyor240 : public PingDevice
{
public:
    /**
     *  @brief Constructor
     *
     *  @param ser: The device I/O
     */
    Surveyor240(PingPort& port) : PingDevice(port) {}

    /**
     * @brief Destructor
     */
    ~Surveyor240();

    /**
     *  @brief Establish communications with the device, and initialize the update interval
     *
     *  @param pingIntervalMs: The interval (in milliseconds) between acoustic measurements
     *
     *  @return true if the device was initialized successfully
     */
    bool initialize();

    /**
     * @brief The first octet of the IP address is placed in the least significant byte of the u32. For example, the IP address 192.168.2.2 would be packed into a u32 like this: u32 ip = (192) | (168 << 8) | (2 << 16) | (2 << 24);
     *
     * @param ntp_ip_address - IP address of NTP server.
     * @param subnet_mask - Subnet of NTP server.
     * @param gateway_ip - Gateway IP address of NTP server. Only necessary if NTP server is in different subnet than device and needs to be accessed through a gateway. Otherwise can be left as 0
     */
    void set_set_net_info(uint32_t ntp_ip_address, uint32_t subnet_mask, uint32_t gateway_ip);

    /**
     * @brief Used to control the operation of Surveyor
     *
     * @param start_mm - Units: mm; Start range in mm at which echo data is recorded. Ignored in auto range mode. Will be forced to 5% of end range as a minimum.
     * @param end_mm - Units: mm; End range in mm over which echo data is recorded. Set to 0 for Surveyor to automatically track the bottom and adjust range dynamically.
     * @param sos_mps - Units: m/s; Speed of sound
     * @param gain_index - Set to -1 for auto gain (recommended). Valid manual gain ranges are from 0 to 100
     * @param msec_per_ping - Units: ms/ping; pings per second = 1000 / msec_per_ping. So 100 msec_per_ping means 10 pings per second. Actual ping rate can be limited by range and speed of sound, so the value specified defines an upper limit on ping rate.
     * @param deprecated - Set to 0
     * @param diagnostic_injected_signal - must be set to 0
     * @param ping_enable - true to start/continue pinging, false to stop
     * @param enable_channel_data - Used by SonarView, but not necessary. If enabled log files will be much larger.
     * @param reserved_for_raw_data - Must be set to false
     * @param enable_yz_point_data - Angle and time of flight data is preferred for future SonarView enhancements.
     * @param enable_atof_data - Enable angle and time of flight information for each detected point
     * @param target_ping_hz - Set to 240000. Used for internal production testing only
     * @param n_range_steps - Sets range resolution in number of range steps. Must be between 200 and 800 (inclusive)
     * @param reserved - 
     * @param pulse_len_steps - Pulse length in number of range steps. Recommended value is 1.5
     */
    void set_set_ping_parameters(int32_t start_mm, int32_t end_mm, float sos_mps, int16_t gain_index, int16_t msec_per_ping, uint16_t deprecated, uint8_t diagnostic_injected_signal, bool ping_enable, bool enable_channel_data, bool reserved_for_raw_data, bool enable_yz_point_data, bool enable_atof_data, int32_t target_ping_hz, uint16_t n_range_steps, uint16_t reserved, float pulse_len_steps);

    /**
     * @brief 
     *
     * @param utc_msec - 
     * @param accuracy_msec - 
     */
    void set_utc_response(uint64_t utc_msec, uint32_t accuracy_msec);



    //! A response packet Surveyor sends to the host application containing angle and time of flight for each detected point.
    struct {
        // Time at start of ping, msec since power on.
        uint32_t pwr_up_msec;
        // Time at start of ping, utc msec (1970 epoc). Will be 0 if not avaliable.
        uint64_t utc_msec;
        // Time from start of ping to last range bin.
        float listening_sec;
        // Speed of sound (mps) used in angle calculations.
        float sos_mps;
        // Assigned sequentially from power on.
        uint32_t ping_number;
        // Frequency of the ping signal (Hz).
        uint32_t ping_hz;
        // Pulse length in seconds.
        float pulse_sec;
        // reserved
        uint32_t flags;
        // Number of points reported in the points field
        uint16_t num_points;
        // 
        uint16_t reserved;
        // 
        atof_t* atof_point_data = nullptr;
        uint32_t atof_point_data_length = 0;
    } atof_point_data_data;

    //! A response packet Surveyor sends to the host application containing information about the attitude (pitch and roll) of the device based on it's internal sensors.
    struct {
        // World up vector (x, y, z) in the device coordinate system (x forward, y port, z up)
        float up_vec_x;
        // World up vector (x, y, z) in the device coordinate system (x forward, y port, z up)
        float up_vec_y;
        // World up vector (x, y, z) in the device coordinate system (x forward, y port, z up)
        float up_vec_z;
        // reserved for future magnetic field vector
        float reserved_1;
        // reserved for future magnetic field vector
        float reserved_2;
        // reserved for future magnetic field vector
        float reserved_3;
        // utc msec (1970 epoc). Will be 0 if not avaliable
        uint64_t utc_msec;
        // msec since power up
        uint32_t pwr_up_msec;
    } attitude_report_data;

    //! A response packet Surveyor sends to the host application containing information about the temperature and pressure of the water.
    struct {
        // 
        float temperature;
        // 
        float pressure;
    } water_stats_data;

    //! A response packet that Surveyor sends to the host application containing the detected depth points.
    struct {
        // msec since power up
        uint32_t timestamp_msec;
        // Assigned sequentially from power on.
        uint32_t ping_number;
        // Speed of sound
        float sos_mps;
        // World up vector (x, y, z) in the device coordinate system (x forward, y port, z up)
        float up_vec_x;
        // World up vector (x, y, z) in the device coordinate system (x forward, y port, z up)
        float up_vec_y;
        // World up vector (x, y, z) in the device coordinate system (x forward, y port, z up)
        float up_vec_z;
        // reserved for future magnetic field vector
        float mag_vec_x;
        // reserved for future magnetic field vector
        float mag_vec_y;
        // reserved for future magnetic field vector
        float mag_vec_z;
        // 
        uint32_t reserved_0;
        // 
        uint32_t reserved_1;
        // 
        uint32_t reserved_2;
        // 
        uint32_t reserved_3;
        // 
        uint32_t reserved_4;
        // 
        uint32_t reserved_5;
        // 
        uint32_t reserved_6;
        // 
        uint32_t reserved_7;
        // 
        uint32_t reserved_8;
        // 
        uint32_t reserved_9;
        // -1000 if sensor not installed
        float water_degC;
        // Water pressure in bar. -1000 if sensor not installed
        float water_bar;
        // Reserved for heave in meters.
        float heave_m;
        // Range at the beginning of the analyzed signals for this ping.
        float start_m;
        // Range at the end of the analyzed signals for this ping.
        float end_m;
        // 
        uint16_t unused;
        // Number of points reported in the points field
        uint16_t num_points;
        // Y and Z value pairs for each detected point. Y is athwartships offset in meters, positive to the port side. Z is depth, positive up so all z values will be negative.
        float* yz_point_data = nullptr;
        uint32_t yz_point_data_length = 0;
    } yz_point_data_data;


private:
    /**
     *  @brief Handle an incoming message from the device. Internal values are updated according to the device data.
     *
     *  @param message: A pointer to the message received from the device
     */
    void _handleMessage(const ping_message* message) override;
};
